apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
  namespace: dotnet-app-ns
  labels:
    app: dotnet-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: dotnet-app
          image: rajivgogia/productmanagementapi:i-rajivgogia-develop-latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
  namespace: dotnet-app-ns
spec:
  type: NodePort
  selector: 
    app: dotnet-app
  ports:    
  - protocol: TCP
    nodePort: 30158
    port: 80
    targetPort: 80
